@url = https://effective-space-cod-q7pxrpgpq5qvc97w4-8080.app.github.dev

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGQVRFQyBBUEkiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc0NjU3NDUwNH0.DjwiA0PmahVhUCMZeuut8Zf6hl2TATc3-TrNrgAxTvk
GET {{url}}/categorias
Authorization:  Bearer {{token}}

###
POST {{url}}/categorias
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Ciencias Exatas"
}